### PR TITLE
use bundler / cleanup rakefile

### PR DESCRIPTION
**Pull request by grosser**
@jeremyevans 

 - reusing rdoc options from gemspec
 - removing if/else gem logic
 - use `rake release` to release new gem
 - use test task
 - require helper in all tests

### CODE REVIEW

**Comment by jeremyevans** [comment]
Thanks for the patch.  Unfortunately, I don't want to depend on bundler, and I want to keep compatibility with ruby 1.8.7 just like minitest, so `require_relative` is out . The changes to use a helper and the gemspec are OK, but I don't think I want to modify the Rakefile as you have done.

**Comment by grosser** [comment]
are you actually still using ruby 1.8 oO
both 1.8 and 1.9 are end of life, so nobody 'should' be using them ...
especially not someone who wants to install some fancy hooks gem ;)
... added back 1.8 support ...

How about treating bundler as just another gem
-> use gem-tasks but don't use bundler/setup ?
(see latest changes)

Can you point me to the Rakefile parts you don't like ?

**Comment by jeremyevans** [comment]
I test all of my gems on 1.8.7. As long as minitest supports 1.8.7, minitest-hooks will also support it.  There's nothing in the gem that would really benefit from 1.9+ features, anyway.

I don't want to rely on bundler at all.  Call me old fashioned. If you remove bundler from the Rakefile, the other parts I don't like are using rake/testtask (not really any simpler in this case), and relying on rdoc/task and not falling back to rake/rdoctask means it won't work on a default ruby 1.8.7 install.

**Comment by grosser** [comment]
I assumed nobody needs to generate rdoc on 1.8 -> useless added complexity

**Pull request closed without merging**
