### PR TITLE
prevent overwriting with multiple hooks and add an easy way to define…

### PR DESCRIPTION
**Pull request by grosser**
… multiple hooks

@jeremyevans 

 - blow up nicely when trying to use multiple blocks (splitting them for readability or by having test macros)
 - add easy way to add multiple hooks

### CODE REVIEW

**Comment by jeremyevans** [comment]
Thanks for the patch.  Unfortunately, I'm against this as it doesn't mirror how minitest's before/after hooks work, and I want to follow the minitest semantics as closely as possible.

**Comment by grosser** [comment]
I'd recommend to at least add the raise so ppl don't run into this without
a warning ...

**Comment by jeremyevans** [comment]
But raising is not how minitest's before/after hooks operate.  I believe if you run in `-w` mode, defining the same hook multiple times in the same class does warn due to the method being overwritten.

**Comment by grosser** [comment]
Just because it's not how minitest does it, does not mean it's a bad idea.
Building things that only work when you run in -w is not very helpful to
most ppl.
I don't think there is a legitimate usecase for overwriting setup/teardown,
I so far only see it happen by accident, because people use what looks
intuitive -> intuitive things should work (->include module) ... or at
least warn you when they dont (-> raise)

**Comment by jeremyevans** [comment]
I didn't say it was a bad idea.  It is a fine idea, it just doesn't mirror minitest's behavior, and that's one of the goals for this library. If you want, you can write your own gem that does that.  You could include a module that does that after including Minitest::Hooks, and either raise or use a module instead of calling super.

**Pull request closed without merging**
