### PR TITLE
Fix reporters by using Minitest::Result for hook errors

### PR DESCRIPTION
**Pull request by GUI**
If an error is encountered in the `before_all`, `after_all`, or `around_all` hooks, then some reporters may not work as expected:

1. The default reports might not print a useful error message or backtrace, instead printing output with indecipherable class/method names, like:

   ```
   Finished in 0.001594s, 627.3526 runs/s, 0.0000 assertions/s.

     1) #<#<Class:0x00007f8ed20d2088>:0x00007f8ed4190f68>

   1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
   ```

2. Reporters expecting each error result to respond to `#source_location` (or the result's `#name` to just be a method name that can be looked up), will break.

   minitest-ci is one such reporter that breaks when errors are thrown in minitest-hook's callbacks (since the object doesn't respond to `source_location` and it's `name` isn't a valid method name that can be looked up): https://github.com/circleci/minitest-ci/blob/8b72b0f32f154d91b53d63d1d0a8a8fb3b01d726/lib/minitest/ci_plugin.rb#L136-L140

Both issues can be solved by recording a `Minitest::Result` instance when errors are encountered by these hooks, which is what minitest (and other reporters) seems to normally expect. You can see that for normal test runs, minitest expects to be sending `reporter.record` a `Minitest::Result` instance:

https://github.com/seattlerb/minitest/blob/1146f43e56e8b6decd2c8ddd88d9fd9b9d3deedb/lib/minitest.rb#L334
https://github.com/seattlerb/minitest/blob/1146f43e56e8b6decd2c8ddd88d9fd9b9d3deedb/lib/minitest.rb#L961

The `Result` class also seems to expect that `name` just be set to the method name (rather than including the class description), in which case, it's then able to properly determine the `source_location` data, and print friendlier error messages in the default reporters. The above example's output (from the test suite) becomes:

```
Finished in 0.001569s, 637.3486 runs/s, 0.0000 assertions/s.

  1) Error:
Minitest::Hooks error handling#around_all:
RuntimeError:
    spec/errors/example.rb:37:in `block (2 levels) in <main>'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

This does change the existing behavior of `#name` slightly, but it seems like the new behavior is what's expected from minitest plugins or reporters.

### CODE REVIEW

**Comment by jeremyevans** [comment]
Great work on this!  This change requires minitest 5.11+, but I'm guessing that is an acceptable.  If not, people can use an older version of minitest-hooks.  I'll do some testing with this on Monday and assuming no issues will release 1.5.0 with this change.

**Comment by GUI** [comment]
Ah, I completely missed that `Minitest::Result` was new, but thanks for catching that! If you're okay with bumping the minitest version requirement, then it does seem like `Minitest::Result` will hopefully be the more stable interface for this type of thing in the future.

But if you'd prefer to keep compatibility with older versions of minitest, I'm also happy to tweak this pull request to only use `Minitest::Result` when using newer versions of minitest. I think the changes to `name`, should possibly remain in older versions, though, but I'd need to play around a bit more (ie, so this logic for older minitest versions would work: https://github.com/circleci/minitest-ci/blob/8b72b0f32f154d91b53d63d1d0a8a8fb3b01d726/lib/minitest/ci_plugin.rb#L139)

**Comment by jeremyevans** [comment]
I don't think keeping backwards compatibility is strictly necessary in this case, but if you want to try getting it to work in older versions of minitest, there may be some users who would appreciate it.

**Comment by GUI** [comment]
I've pushed a further change that maintains compatibility with Minitest pre 5.11:

- It turns out the error message display issue (the error name showing up like `#<#<Class:0x00007f8ed20d2088>:0x00007f8ed4190f68>`) was a new issue in Minitest 5.11 with minitest-hooks. Prior versions did display correctly, but using `Minitest::Result` does fix this in Minitest 5.11+.
- I think changing how `name` is set is still relevant for all versions of Minitest, since other reporters seem to expect that this is just the method name (rather than a display name including the class). This was the underlying issue behind minitest-ci breaking when used with minitest-hooks regardless of Minitest version.
- I setup [Appraisal](https://github.com/thoughtbot/appraisal) to make testing against multiple versions of Minitest easier, as well as [TravisCI](https://travis-ci.org/GUI/minitest-hooks/builds/381191838) to run the tests. I may have gone overboard with testing multiple versions of Ruby and Minitest on TravisCI, so if you want to speed up those runs, we could pare down all the combinations.
- I tweaked the gemspec to shift minitest to a direct dependency, rather than a development dependency, but let me know if keeping it as a development dependency was intentional.
- I also got rid of the deprecated `has_rdoc` setting in the gemspec, since that was generating rubygems warnings in some versions, which could impact the tests.

Let me know if you'd like for me to squash this to a single commit, or have any other suggestions. Thanks for taking a look and for this gem!

**Comment by jeremyevans** [comment]
Thanks for the changes, especially adding backwards compatibility.  I'm not sure I want to use Appraisal, but I definitely think it makes sense to add TravisCI considering how popular minitest-hooks has become. I'll take a deeper look at these changes on Monday.

**Pull request merged**
