### PR TITLE
ship only necessary files

### PR DESCRIPTION
**Pull request by grosser**
@jeremyevans very few people open gems and even fewer need any of these files -> optimize for that 99.x% usecase and reduce filesize on disk + size of vendored gems

### CODE REVIEW

**Comment by jeremyevans** [comment]
I appreciate that few people use these files, but I think it's important to ship them.  I ship specs for all of my gems.  That way it is easy for packagers to run tests on the gem to ensure it works correctly.  As I handle packaging ruby gems on OpenBSD, if the gem doesn't include specs, it's basically impossible for me to test it to make sure it works correctly on OpenBSD.

**Comment by grosser** [comment]
Tons of gems don't ship specs or their specs don't work with manual setup
-> at best a flaky manual process.

Did you ever find a gem test bug and concluded "This must be an openbsd
issue I better tell that gem author" ?

**Comment by jeremyevans** [comment]
Yes, I've found issues and reported them upstream. It's not frequent, but it does happen, usually when dealing with C extensions, which are often written with just Linux/Mac in mind.

**Comment by jeremyevans** [comment]
Note that minitest itself ships its Rakefile and tests in its gem.  If you can convince minitest to not ship the Rakefile and tests in its gem, I will follow suit.

**Comment by grosser** [comment]
I'm not touching that junkyard of a gem directly, got burnt too often :D

**Pull request closed without merging**
